---
title: "CMAR Coastal Monitoring Program User Statistics"
format: 
  dashboard:
    orientation: columns
    theme: custom.scss
server: shiny
---

```{r}
#| context: setup
#| include: false

library(bsicons)
library(bslib)
library(dplyr)
library(ggplot2)
library(here)
library(lubridate)
library(plotly)
library(RColorBrewer)
library(RSocrata)
library(shiny)
library(stringr)
library(tidyr)

source(here("functions/preprocess_user_stats.R"))

theme_set(theme_light())

#dat_all <- readRDS(here("data/historical_access.RDS")) 

pal <- c("#063E4D", "#62AECA")

```

# Filters {.sidebar width=15% height=100%}

**Download User Statistics**

The User Statistics must be loaded at the beginning of each session. This may take
30 - 60 seconds.

```{r}
w <- '95%'

actionButton("button", "Load Data", width = w, class = "btn-primary btn-lg")
```
<br>

**Select Statistics**

```{r}
selectInput(
  "data_branch", "Select Data Branch", 
  #choices = unique(dat_all$program_branch),
  choices = c("Current", "Water Quality", "Wave"),
  selected = "Water Quality"
)

selectInput(
  "data_product", "Select Data Product", 
  # choices = unique(dat_all$data_product),
  choices = c("chart", "dataset", "map"),
  selected = "dataset"
)

selectInput(
  "access_type", "Select Access", 
  #choices = unique(dat_all$access_type),
  choices = c("API read", "download", "view"),
  selected = "download"
)
```

# Dashboard

## 
```{r}
plotlyOutput("fig1")
```

##

### {height=70%}
```{r}
plotlyOutput("fig2")
```

###

::: {.card padding=0px}
```{r}

uiOutput("value_box_total")

```
:::


```{r}
#| context: server

dat_all <- eventReactive(input$button, {
  
  withProgress(
    message = 'Loading data', 
    detail = 'This may take a moment...', {
      
      odp_api_config <- config::get(config = "default", file = "odp_api/config.yml")
      
      wq_metrics_url <- "https://data.novascotia.ca/api/v3/views/ktyz-sxuu/"
      adcp_metrics_url <- "https://data.novascotia.ca/api/v3/views/dv55-4vcp/"
      
      wq_metrics <- read.socrata(
        wq_metrics_url,
        app_token = odp_api_config$app_token,
        email = odp_api_config$email,
        password = odp_api_config$password
      )
      
      incProgress(1/2, detail = "halfway there")
      
      adcp_metrics <- read.socrata(
        adcp_metrics_url,
        app_token = odp_api_config$app_token,
        email = odp_api_config$email,
        password = odp_api_config$password
      )
      
      dat_all <- bind_rows(wq_metrics, adcp_metrics) %>%
        preprocess_user_stats()
      
    })
  
  return(dat_all)
  
})


dat <- reactive({
  req(dat_all())
  
  dat <- dat_all() %>% 
    filter(
      program_branch == input$data_branch,
      access_type == input$access_type,
      data_product == input$data_product
    ) 

  return(dat)
})

output$fig1 <- renderPlotly({
  
  plot_title <- paste0(
    "Number of ",
    input$data_branch, " ",
    input$data_product, "\n", 
    input$access_type, "s"
  )
  
  dat_plot <- dat() %>% 
    group_by(asset_name) %>% 
    summarise(n = sum(value)) %>% 
    ungroup()
  
  p <- ggplot(dat_plot, aes(n, asset_name)) +
    geom_col(position = "dodge", col = "grey20", fill = pal[1]) +
    scale_y_discrete(limits = rev) +
    scale_x_continuous("Total Number", expand = expansion(mult = c(0, 0.1))) +
    labs(title = plot_title) +
    theme(
      plot.title = element_text(hjust = 0),
      panel.grid.major.y = element_blank(),
      axis.title.y = element_blank()
    )
  
  ggplotly(p) %>% 
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = paste(
          "total",
          input$data_branch, 
          input$data_product, 
          input$access_type,  
          sep = "_"),
        width = 600, height = 800
      ))
})

# could make this daily
output$fig2 <- renderPlotly({
  plot_title <- paste0(
    "Cumulative number of ",
    input$data_branch, " ",
    input$data_product, " ",
    input$access_type, "s"
  )
  
  dat_plot <- dat() %>%
    arrange(timestamp) %>% 
    group_by(asset_name) %>%
    mutate(n = cumsum(value)) %>% 
    ungroup()
  
  get_pal <- colorRampPalette(c("#063E4D", "#62AECA", "#FFD118"))
  pal <- get_pal(length(unique(dat_plot$asset_name)))
  
  p <- ggplot(
    dat_plot, 
    aes(timestamp, n, col = asset_name, group = asset_name,
        text = paste(
          "asset_name: ", asset_name, "\n",
          "timestamp: ", timestamp, "\n",
          "cumulative number: ", n
        ))
  ) +
    geom_line(linewidth = 1) +
    scale_y_continuous("Cumulative Number") +
    scale_colour_manual("Asset", values = pal) +
    labs(title = plot_title) +
    theme(axis.title.x = element_blank())
  
  ggplotly(p, tooltip = "text") %>% 
    config(
      modeBarButtonsToRemove = list("toggleSpikelines", "autoScale2d"),
      displaylogo = FALSE,
      toImageButtonOptions = list(
        format = "png",
        filename = paste(
          "cumulative",
          input$data_branch, 
          input$data_product, 
          input$access_type,  
          sep = "_"),
        width = 1200, height = 600
      ))
})

#####################################################
###### VALUE BOX ####################################
#####################################################
box_title <- reactive({
  box_title <- paste0(
    "Total ",
    input$data_branch, " ",
    input$data_product, "\n", 
    input$access_type, "s"
  )
  
  return(box_title)
})

box_value <- reactive({
  
  n <- dat() %>% 
    summarise(n = sum(value)) %>% 
    pull(n)

  n <- format(n, big.mark = ",")
  return(n)
})

box_icon <- reactive({
  
  if(grepl("view", input$access_type)) {
    box_icon <- "eye"
  } else if(grepl("download", input$access_type)) {
    box_icon <- "box-arrow-down"
  } else box_icon <- "book"
  
  return(box_icon)
})

output$value_box_total <- renderUI({
  
  bslib::value_box(
    title = box_title(),
    showcase = bs_icon(box_icon()),
    value = box_value(),
    theme = value_box_theme(bg = "#62AECA", fg = "#063E4D")
  )
  
})

```
